name: detect environment
description: Detect environment

outputs:
  environment:
    description: The environment key
    value: ${{ steps.get-environment.outputs.environment }}

runs:
  using: composite
  steps:
    - id: get-environment
      shell: bash
      run: |
        if [ "${{ github.event.label.name }}" == "ready to test" ]; then
          echo "environment=nonprod" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "ready to deploy" ]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        fi