name: detect environment
description: Detect environment

outputs:
  environment:
    description: The environment key
    value: ${{ steps.get-environment.outputs.environment }}

#TODO: Check from branch feature/* nonprod
#TODO: Check from branch release/* prod
runs:
  using: composite
  steps:
    - name: Get environment
      id: get-environment
      shell: bash
      run: |
        if [ "${{ github.event.pull_request.base.ref }}" == "develop" ]; then
          echo "environment=nonprod" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.pull_request.base.ref }}" == "main" ]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        fi
        
