name: dotnet migration
description: Migrate .NET Core project

inputs:
  repository:
    description: The owner and repository name
    required: false
    default: ${{ github.repository }}
  target_ref:
    required: false
    description: The branch or tag ref or commit SHA that will be merged to base code.
    default: ${{ github.head_ref || github.ref_name }}
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: false
    default: ${{ github.base_ref || 'main' }}
  dotnet_version:
    description: The version of .NET Core SDK
    required: true
  dotnet_project_path:
    description: The path of .NET Core project
    required: true
  dotnet_migration_enabled:
    description: Enable migration
    required: false

runs:
  using: composite
  steps:
    - name: Setup
      uses: jiw-kittipong/github-action-workflows/language/dotnet/setup@main
      with:
        repository: ${{ inputs.repository }}
        base_ref: ${{ inputs.base_ref }}
        target_ref: ${{ inputs.target_ref }}
        dotnet_version: ${{ inputs.dotnet_version }}
        dotnet_project_path: ${{ inputs.dotnet_project_path }}

    - name: Migration
      working-directory: ${{ inputs.dotnet_project_path }}
      shell: bash
      run: |
        echo "dotnet migration"
