name: deploy

inputs:
  version:
    description:  "Version"
    required:  true

runs:
  using: composite
  steps:
    - name: deploy
      shell: bash
      run: |
        echo "HELLO WORLD"
        CALL PATCH IMAGE TAG IN ARGO ${{ github.sha }}
        {{ inputs.version }} 
