name: deploy
description: "Deploy"

inputs:
  version:
    description:  "Version"
    required:  true

runs:
  using: composite
  steps:
    - name: deploy
      shell: bash
      run: |
        echo "HELLO WORLD" ${{ inputs.version }} 
