name: dotnet setup
description: Setup .NET Core project

inputs:
  repository:
    description: The owner and repository name
    required: false
    default: ${{ github.repository }}
  target_ref:
    required: false
    description: The branch or tag ref or commit SHA that will be merged to base code.
    default: ${{ github.head_ref || github.ref_name }}
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: false
    default: ${{ github.base_ref || 'main' }}
  dotnet_version:
    description: The version of .NET Core SDK
    required: true
  dotnet_project_path:
    description: The path of .NET Core project
    required: true

runs:
  using: composite
  steps:
    - uses: jiw-kittipong/github-action-workflows/checkout@main
      with:
        repository: ${{ inputs.repository }}
        base_ref: ${{ inputs.base_ref }}
        target_ref: ${{ inputs.target_ref }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Install dependencies
      working-directory: ${{ inputs.dotnet_project_path }}
      shell: bash
      run: |
        dotnet restore .
