name: dotnet setup
description: Setup .NET Core project

inputs:
  repository:
    description: The owner and repository name
    required: false
    default: ${{ github.repository }}
  target_ref:
    required: false
    description: The branch or tag ref or commit SHA that will be merged to base code.
    default: ${{ github.head_ref || github.ref_name }}
  base_ref:
    description: The branch or tag ref or commit SHA that be base code.
    required: false
    default: ${{ github.base_ref || 'main' }}
  dotnet_version:
    description: The version of .NET Core SDK
    required: true
  dotnet_project_path:
    description: The path of .NET Core project
    required: true

runs:
  using: composite
  steps:
    - uses: jiw-kittipong/github-action-workflows/checkout@main
      with:
        repository: ${{ inputs.repository }}
        base_ref: ${{ inputs.base_ref }}
        target_ref: ${{ inputs.target_ref }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - uses: jungwinter/split@master
      id: project_file
      with:
        msg: ${{ inputs.dotnet_project_path }}
        separator: "/"
#        maxsplit: -1

    - name: Install dependencies
      shell: bash
      run: echo "${{ steps.project_file.outputs._n }}"
