name: dotnet CI/CD

on:
  workflow_call:
    inputs:
      repository:
        description: The owner and repository name
        required: false
        type: string
        default: ${{ github.repository }}
      base_ref:
        description: The branch or tag ref or commit SHA that be base code.
        required: false
        type: string
        default: ${{ github.base_ref || 'main' }}
      target_ref:
        description: The branch or tag ref or commit SHA that will be merged to base code.
        required: false
        type: string
        default: ${{ github.head_ref || github.ref_name }}
      application_name:
        description: Name of application
        required: true
        type: string
      code_language:
        description: The program language of this repository
        required: true
        type: string
      dotnet_version:
        description: The version of .NET Core SDK
        required: false
        type: string
        default: "6.0"
      dotnet_project_path:
        description: The path of .NET Core project
        required: true
        type: string

    secrets:
      aws_access_key_id:
        description: AWS access key ID
        required: true
      aws_secret_access_key:
        description: AWS secret access key
        required: true

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Lint
#      uses: jiw-kittipong/github-action-workflows/language/dotnet/lint@main

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: jiw-kittipong/github-action-workflows/language/dotnet/test@main

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Build image
        uses: jiw-kittipong/github-action-workflows/language/dotnet/build@main
        with:
          target_ref: ${{ inputs.target_ref }}
          application_name: ${{ inputs.application_name }}
          dotnet_version: ${{ inputs.dotnet_version }}
          dotnet_project_path: ${{ inputs.dotnet_project_path }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Deploy ${{ inputs.application_name }}
        uses: jiw-kittipong/github-action-workflows/deploy@main